// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A unified structure for successful API responses.
 */
export type ApiResponse<T> = {
    /**
     * Business status code. 0 for success.
     */
    code: number;
    /**
     * Response message.
     */
    message: string;
    /**
     * Response data.
     */
    data: T;
    /**
     * Total number of items.
     */
    total: number | null;
};
