// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserStatus } from "./UserStatus";

/**
 * Create user request parameters
 */
export type CreateUserDto = {
    username: string;
    email: string;
    password: string;
    realName: string | null;
    /**
     * User status. Defaults to Normal.
     */
    status: UserStatus | null;
    /**
     * A list of role IDs to assign to the user. If empty, will use default role.
     */
    roleIds: Array<number>;
};
