// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create and update role request parameters
 */
export type CreateRoleDto = { name: string, code: string, status: number, sortOrder: number | null, menuIds: Array<number>, description: string | null, };
