// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create menu request parameters
 */
export type CreateMenuDto = {
    parentId: number;
    name: string;
    code: string;
    menuType: number;
    sortOrder: number;
    status: number;
};
