// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for dict options endpoints
 */
export type DictOptionsQuery = { dict_type: string | null, q: string | null, limit: number | null, };
