// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dictionary query parameters
 */
export type DictQuery = {
    /**
     * The page number to retrieve. Defaults to 1.
     */
    current: number | null;
    /**
     * The number of items per page. Defaults to 10.
     */
    pageSize: number | null;
    /**
     * Filter by dictionary type.
     */
    dictType: string | null;
    /**
     * Filter by label.
     */
    label: string | null;
    /**
     * Filter by value.
     */
    value: string | null;
    /**
     * Filter by status.
     */
    status: string | null;
};
