// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserInfoResp } from "./UserInfoResp";

/**
 * Response payload for successful user login.
 */
export type LoginResp = {
    /**
     * JWT token for authenticating subsequent requests
     */
    token: string;
    /**
     * User information
     */
    userInfo: UserInfoResp;
};
