// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for user authentication.
 */
export type LoginRequest = {
    /**
     * Username or email for authentication
     */
    username: string;
    /**
     * User's password in plain text
     */
    password: string;
};
