// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Log query parameters
 */
export type LogQuery = {
    current: number | null;
    pageSize: number | null;
    username: string | null;
    action: string | null;
    description: string | null;
    ipAddress: string | null;
};
