// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Menu item for tree list display
 */
export type MenuItemResp = {
    id: number;
    parentId: number;
    name: string;
    code: string;
    menuType: number;
    status: number;
    isSystem: boolean;
    sortOrder: number;
    createdAt: string;
    updatedAt: string;
    children: Array<MenuItemResp> | null;
};
