// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Menu tree option item for permission selection
 */
export type MenuTreeOption = {
    label: string;
    value: number;
    code: string;
    parentId: number;
    menuType: number;
    children: Array<MenuTreeOption> | null;
};
