// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Menu query parameters
 */
export type MenuQuery = { 
/**
 * The name of the menu.
 */
name: string | null, 
/**
 * The code of the menu.
 */
code: string | null, 
/**
 * The status of the menu.
 */
status: string | null, 
/**
 * The type of the menu.
 */
menuType: number | null, };
