// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Menu type enum constants
 */
export type MenuType = "Directory" | "Menu" | "Button";
