// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A generic structure for dropdown options.
 */
export type OptionItem<T> = { label: string; value: T };
