// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for options with code endpoints
 */
export type OptionsWithCodeQuery = {
    q?: string;
    limit?: number;
    /**
     * Whether to filter out button menus
     */
    btn_filter?: boolean;
};
