// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OptionItem } from "./OptionItem";

/**
 * Role item for list display
 */
export type RoleItemResp = { id: number, name: string, code: string, description: string | null, status: number, sortOrder: number, createdAt: string, updatedAt: string, menus: Array<OptionItem<number>>, };
