// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsResp = {
    totalUsers: number;
    activeUsers: number;
    todayLogins: number;
    systemUptime: string;
    pendingUsers: number;
};
