// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemInfo = {
    memoryTotal: number;
    memoryUsed: number;
    memoryFree: number;
    cpuTotal: number;
    cpuUsed: number;
    diskTotal: number;
    diskUsed: number;
    diskFree: number;
};
