// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update menu request parameters
 */
export type UpdateMenuPayload = { parentId: number, name: string, code: string, menuType: number, sortOrder: number, status: number, };
