// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Updates the status of a dictionary item.
 */
export type UpdateDictStatusPayload = { status: number };
