// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update dictionary item request parameters
 */
export type UpdateDictPayload = { dictType: string, label: string, value: string, status: number | null, description: string | null, sortOrder: number | null, };
