// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update user request parameters
 */
export type UpdateUserPayload = { email: string, realName: string | null, 
/**
 * A list of role IDs to assign to the user. If provided, replaces all existing roles.
 */
roleIds: Array<number>, };
