// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update role request parameters
 */
export type UpdateRolePayload = {
    name: string;
    code: string;
    status: number;
    sortOrder: number | null;
    menuIds: Array<number>;
    description: string | null;
};
