// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrendResp } from "./TrendResp";

export type UserTrendsResp = { dailyLogins: Array<TrendResp>, hourlyActive: Array<TrendResp>, };
