// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User status enum for authentication and account control.
 */
export type UserStatus = "Normal" | "Disabled" | "Pending" | "Locked";
