// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User options query parameters
 */
export type UserOptionsQuery = {
    /**
     * Search keyword
     */
    q: string | null;
    /**
     * Maximum number of results to return
     */
    limit: number | null;
    /**
     * Filter by user status
     */
    status: number | null;
};
