// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User list query parameters
 */
export type UserQuery = {
    /**
     * The page number to retrieve. Defaults to 1.
     */
    current: number | null;
    /**
     * The number of items per page. Defaults to 10.
     */
    pageSize: number | null;
    /**
     * Filter by username (case-insensitive search).
     */
    username: string | null;
    /**
     * Filter by user status. Accepts: "normal"/"1", "disabled"/"2", or "all".
     */
    status: string | null;
    /**
     * Filter by real name (case-insensitive search).
     */
    realName: string | null;
    /**
     * Filter by email (case-insensitive search).
     */
    email: string | null;
};
